// ============================================================
// Additional California County Jurisdiction Profiles
// ============================================================
// 55 counties NOT already defined in jurisdictions.ts
// (Fresno, Merced, and Stanislaus are defined there)
// ============================================================

import type { JurisdictionProfile } from './jurisdictions';

export const ADDITIONAL_COUNTIES: JurisdictionProfile[] = [
  // ── LETTER GRADE SYSTEMS ──────────────────────────────────

  {
    id: 'county-la',
    name: 'Los Angeles County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'letter_grade',
      details: 'Letter grade system with grade card prominently displayed at entrance visible to patrons. Cities with independent health departments (Long Beach, Pasadena, Vernon) are excluded from county jurisdiction.',
      grades: [
        { label: 'A', range: '90-100' },
        { label: 'B', range: '80-89' },
        { label: 'C', range: '70-79' },
        { label: 'Score Card', range: 'Below 70' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Los Angeles County Dept of Public Health, Environmental Health Division',
      phone: '(888) 700-9995',
      website: 'https://ehservices.publichealth.lacounty.gov/',
      inspectionFrequency: 'Risk-based: high risk 1-3 times per year',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Grade card must be posted at entrance visible to patrons at all times',
      'Cities of Long Beach, Pasadena, and Vernon operate independent health departments — not under LA County jurisdiction',
      'Re-inspection required for any grade below A',
      'Facilities receiving a score below 70 may face closure',
    ],
  },

  {
    id: 'county-san-diego',
    name: 'San Diego County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'letter_grade',
      details: 'Letter grade system based on scored inspections. Major Risk Factor = 4 pts deducted, Minor Risk Factor = 2 pts, Good Retail Practice = 1 pt. Over 32,000 inspections conducted annually.',
      grades: [
        { label: 'A', range: '90-100' },
        { label: 'B', range: '80-89' },
        { label: 'C', range: '79 or below (failing)' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'San Diego County Dept of Environmental Health and Quality',
      phone: '(858) 505-6900',
      website: 'https://www.sandiegocounty.gov/deh/',
      inspectionFrequency: 'Risk-based: 32,000+ inspections/year countywide',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Major Risk Factor violations carry 4-point deductions',
      'Minor Risk Factor violations carry 2-point deductions',
      'Good Retail Practice violations carry 1-point deductions',
      'Grade C or below is considered failing and triggers enforcement actions',
    ],
  },

  {
    id: 'county-kern',
    name: 'Kern County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'letter_grade',
      details: 'Letter grade system with color-coded placards. Facilities scoring below 75 face closure.',
      grades: [
        { label: 'A / Blue', range: '90-100' },
        { label: 'B / Green', range: '80-89' },
        { label: 'C / Yellow', range: '75-79' },
        { label: 'Closure / Red', range: 'Below 75' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Kern County Public Health Services, Environmental Health',
      phone: '(661) 862-8740',
      website: 'https://kernpublichealth.com/environmental-health/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Color-coded placards accompany letter grades (Blue=A, Green=B, Yellow=C, Red=Closure)',
      'Score below 75 results in closure until corrections are verified',
      'Placard must be posted in a location visible to the public',
    ],
  },

  {
    id: 'county-riverside',
    name: 'Riverside County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'letter_grade',
      details: 'Letter grade system where only Grade A is considered passing. Grades B and C require mandatory re-inspection. "Award of Excellence" given to facilities scoring 95% or above on all inspections.',
      grades: [
        { label: 'A', range: '90-100' },
        { label: 'B', range: '80-89' },
        { label: 'C', range: '79 or below' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Riverside County Dept of Environmental Health',
      phone: '(888) 722-4234',
      website: 'https://www.rivcoeh.org/',
      inspectionFrequency: 'Risk-based: high risk annually, re-inspection for B/C grades',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Only Grade A is considered passing',
      'Grades B and C trigger mandatory re-inspection',
      '"Award of Excellence" recognition for facilities scoring 95% or above on all inspections',
      'Grade card must be conspicuously posted',
    ],
  },

  {
    id: 'county-san-bernardino',
    name: 'San Bernardino County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'letter_grade',
      details: 'Letter grade system established per San Bernardino County Code Chapter 14. Grade card must be publicly displayed.',
      grades: [
        { label: 'A', range: '90-100' },
        { label: 'B', range: '80-89' },
        { label: 'C', range: '79 or below' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'San Bernardino County Environmental Health Services',
      phone: '(800) 442-2283',
      website: 'https://wp.sbcounty.gov/dph/environmental-health-services/',
      inspectionFrequency: 'Risk-based: per County Code Chapter 14',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Letter grade system per County Code Chapter 14',
      'Grade card must be posted in a location visible to the public',
    ],
  },

  {
    id: 'county-alameda',
    name: 'Alameda County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'letter_grade',
      details: 'Letter grade system established by county ordinance. Major CDC Risk Factor violations: 2-4 pts, Minor Retail Practice: 1 pt, Imminent Health Hazard: 26 pts. City of Berkeley operates an independent health department.',
      grades: [
        { label: 'A', range: '90-100' },
        { label: 'B', range: '80-89' },
        { label: 'C', range: '79 or below' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Alameda County Dept of Environmental Health',
      phone: '(510) 567-6700',
      website: 'https://deh.acgov.org/',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Major CDC Risk Factor violations carry 2-4 point deductions',
      'Minor Retail Practice violations carry 1-point deductions',
      'Imminent Health Hazard carries 26-point deduction and possible immediate closure',
      'City of Berkeley operates an independent health department — not under county jurisdiction',
    ],
  },

  // ── COLOR-CODED PLACARD SYSTEMS ───────────────────────────

  {
    id: 'county-sacramento',
    name: 'Sacramento County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'color_placard',
      details: 'Color-coded placard system indicating facility status. Placards must be displayed at entrance.',
      grades: [
        { label: 'GREEN', range: 'Open / Compliant' },
        { label: 'YELLOW', range: 'Conditional / Corrections Required' },
        { label: 'RED', range: 'Closed' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Sacramento County Environmental Management Dept',
      phone: '(916) 875-8440',
      website: 'https://www.saccounty.gov/EMD/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Color-coded placard must be displayed at entrance',
      'Yellow placard requires corrections within specified timeframe',
      'Red placard means facility is closed until violations are corrected and re-inspected',
    ],
  },

  {
    id: 'county-butte',
    name: 'Butte County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'color_placard',
      details: 'Color-coded placard system for approximately 1,200 food facilities countywide.',
      grades: [
        { label: 'GREEN', range: 'Open / Compliant' },
        { label: 'YELLOW', range: 'Conditional' },
        { label: 'RED', range: 'Closed' },
      ],
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Butte County Environmental Health Division',
      phone: '(530) 552-3880',
      website: 'https://www.buttecounty.net/publichealth/environmentalhealth',
      inspectionFrequency: 'Risk-based: approximately 1,200 food facilities',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Color-coded placard system for all food facilities',
      'Approximately 1,200 food facilities under county jurisdiction',
    ],
  },

  // ── PASS/FAIL SYSTEM ──────────────────────────────────────

  {
    id: 'county-orange',
    name: 'Orange County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'pass_fail',
      details: 'Pass/fail placard system with large-font placards implemented October 2024. Placards must be posted at entrance.',
      grades: [
        { label: 'PASS', range: 'Compliant' },
        { label: 'FAIL', range: 'Non-compliant — closure or re-inspection required' },
      ],
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Orange County Environmental Health Division',
      phone: '(714) 433-6000',
      website: 'https://www.ochealthinfo.com/about-hca/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Large-font pass/fail placards implemented October 2024',
      'Placard must be posted at entrance visible to patrons',
      'Failing facilities subject to closure until re-inspection and compliance',
    ],
  },

  // ── STANDARD CALCODE ENFORCEMENT ──────────────────────────

  {
    id: 'county-san-francisco',
    name: 'San Francisco (City & County)',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with SCORES (San Francisco Online Restaurant Inspection Scores) system for public access to inspection results online.',
    },
    minimumWage: {
      general: 19.18,
      source: 'San Francisco Minimum Wage Ordinance',
      effectiveDate: '2025-07-01',
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'San Francisco Dept of Public Health, Environmental Health Branch',
      phone: '(415) 252-3800',
      website: 'https://www.sfdph.org/dph/EH/',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Local minimum wage $19.18/hr (higher than state minimum)',
      'Mandatory composting and recycling for all food service establishments',
      'Health Care Security Ordinance applies to businesses with 20+ employees',
      'SCORES system provides public online access to inspection results',
    ],
  },

  {
    id: 'county-santa-clara',
    name: 'Santa Clara County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement — no mandatory public grading system. Inspection results available upon request.',
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Santa Clara County Dept of Environmental Health',
      phone: '(408) 918-3400',
      website: 'https://www.sccgov.org/sites/deh/',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'No mandatory public grading system',
      'Standard CalCode enforcement with risk-based inspections',
    ],
  },

  {
    id: 'county-contra-costa',
    name: 'Contra Costa County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Contra Costa County Environmental Health Division',
      phone: '(925) 692-2500',
      website: 'https://www.contracosta.ca.gov/1377/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-san-mateo',
    name: 'San Mateo County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'San Mateo County Environmental Health Services',
      phone: '(650) 372-6200',
      website: 'https://www.smchealth.org/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Mobile food facilities limited to 30 minutes in one location',
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-sonoma',
    name: 'Sonoma County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement through Permit Sonoma, Environmental Health division.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Sonoma County Permit Sonoma, Environmental Health',
      phone: '(707) 565-6565',
      website: 'https://sonomacounty.ca.gov/Permit-Sonoma/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-solano',
    name: 'Solano County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Solano County Environmental Health Services',
      phone: '(707) 784-6765',
      website: 'https://www.solanocounty.com/depts/rm/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-napa',
    name: 'Napa County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Napa County Environmental Management',
      phone: '(707) 253-4471',
      website: 'https://www.countyofnapa.org/155/Environmental-Management',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-marin',
    name: 'Marin County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Marin County Environmental Health Services',
      phone: '(415) 473-6907',
      website: 'https://www.marincounty.org/depts/cd/divisions/environmental-health-services',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-ventura',
    name: 'Ventura County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'Ventura County Environmental Health Division',
      phone: '(805) 654-2813',
      website: 'https://vchca.org/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-santa-barbara',
    name: 'Santa Barbara County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Santa Barbara County Environmental Health Services',
      phone: '(805) 681-4900',
      website: 'https://www.countyofsb.org/phd/environmental-health-services',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-san-luis-obispo',
    name: 'San Luis Obispo County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'score_only',
      details: 'New negative scoring system implemented May 2025. "Award of Excellence" program for top-performing facilities. EatSafeSLO interactive map provides public access to inspection data.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'San Luis Obispo County Environmental Health Services',
      phone: '(805) 781-5544',
      website: 'https://www.slocounty.ca.gov/EHS',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'New negative scoring system implemented May 2025',
      '"Award of Excellence" program for consistently high-performing facilities',
      'EatSafeSLO interactive map provides public access to inspection data',
    ],
  },

  {
    id: 'county-monterey',
    name: 'Monterey County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Monterey County Environmental Health Bureau',
      phone: '(831) 755-4505',
      website: 'https://www.co.monterey.ca.us/government/departments-a-h/health/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-santa-cruz',
    name: 'Santa Cruz County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Santa Cruz County Environmental Health',
      phone: '(831) 454-2022',
      website: 'https://www.santacruzhealth.org/HSADivision/EnvironmentalHealth.aspx',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-humboldt',
    name: 'Humboldt County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Humboldt County Environmental Health',
      phone: '(707) 445-6215',
      website: 'https://humboldtgov.org/155/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-mendocino',
    name: 'Mendocino County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Mendocino County Environmental Health',
      phone: '(707) 234-6625',
      website: 'https://www.mendocinocounty.org/government/health-human-services-agency/public-health/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-lake',
    name: 'Lake County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Lake County Environmental Health',
      phone: '(707) 263-1164',
      website: 'https://www.lakecountyca.gov/Government/Directory/Health_Services/Environmental_Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-del-norte',
    name: 'Del Norte County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Del Norte County Environmental Health',
      phone: '(707) 464-0861',
      website: 'https://www.dnco.org/departments/health-human-services/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-siskiyou',
    name: 'Siskiyou County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Siskiyou County Environmental Health',
      phone: '(530) 841-2100',
      website: 'https://www.co.siskiyou.ca.us/publichealth/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-shasta',
    name: 'Shasta County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Shasta County Environmental Health',
      phone: '(530) 225-5787',
      website: 'https://www.co.shasta.ca.us/index/hhsa_index/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-tehama',
    name: 'Tehama County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Tehama County Environmental Health',
      phone: '(530) 527-8020',
      website: 'https://www.tehama.ca.us/departments/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-glenn',
    name: 'Glenn County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Glenn County Environmental Health',
      phone: '(530) 934-6102',
      website: 'https://www.countyofglenn.net/dept/health-human-services/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-colusa',
    name: 'Colusa County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Colusa County Environmental Health',
      phone: '(530) 458-0350',
      website: 'https://www.countyofcolusa.org/149/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-yolo',
    name: 'Yolo County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Yolo County Environmental Health',
      phone: '(530) 666-8646',
      website: 'https://www.yolocounty.org/community-services/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-placer',
    name: 'Placer County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Placer County Environmental Health',
      phone: '(530) 745-2300',
      website: 'https://www.placer.ca.gov/1835/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-el-dorado',
    name: 'El Dorado County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'El Dorado County Environmental Management',
      phone: '(530) 621-5300',
      website: 'https://www.edcgov.us/Government/EMD',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-nevada',
    name: 'Nevada County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Nevada County Environmental Health',
      phone: '(530) 265-1222',
      website: 'https://www.mynevadacounty.com/413/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-sierra',
    name: 'Sierra County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement. Environmental health services contracted through neighboring county due to very limited local resources.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Sierra County Environmental Health (contracted services)',
      phone: 'N/A',
      website: 'N/A',
      inspectionFrequency: 'Risk-based: limited services, contracted through neighboring county',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Environmental health services contracted through neighboring county',
      'Very limited local food safety services due to small population',
      'Standard CalCode enforcement applies',
    ],
  },

  {
    id: 'county-plumas',
    name: 'Plumas County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Plumas County Environmental Health',
      phone: '(530) 283-6355',
      website: 'https://www.plumascounty.us/2027/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-lassen',
    name: 'Lassen County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Lassen County Environmental Health',
      phone: '(530) 251-8528',
      website: 'https://www.lassencounty.org/dept/health-and-social-services/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-modoc',
    name: 'Modoc County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Modoc County Environmental Health',
      phone: '(530) 233-6311',
      website: 'https://www.co.modoc.ca.us/departments/health-services/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-trinity',
    name: 'Trinity County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Trinity County Environmental Health',
      phone: '(530) 623-1459',
      website: 'https://www.trinitycounty.org/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-sutter',
    name: 'Sutter County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Sutter County Environmental Health',
      phone: '(530) 822-7215',
      website: 'https://www.suttercounty.org/government/county-departments/community-services/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-yuba',
    name: 'Yuba County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Yuba County Environmental Health',
      phone: '(530) 749-5450',
      website: 'https://www.yuba.org/departments/community_development/environmental_health/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-amador',
    name: 'Amador County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Amador County Environmental Health',
      phone: '(209) 223-6439',
      website: 'https://www.amadorgov.org/government/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-alpine',
    name: 'Alpine County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement. Smallest county in California with very limited food safety services.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Alpine County Health & Human Services',
      phone: 'N/A',
      website: 'N/A',
      inspectionFrequency: 'Very limited — smallest county in California',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Smallest county in California with very limited food safety services',
      'Standard CalCode enforcement applies',
    ],
  },

  {
    id: 'county-mono',
    name: 'Mono County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Mono County Environmental Health',
      phone: '(760) 932-5580',
      website: 'https://www.monocounty.ca.gov/public-health/page/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-inyo',
    name: 'Inyo County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Inyo County Environmental Health',
      phone: '(760) 873-7868',
      website: 'https://www.inyocounty.us/departments/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-imperial',
    name: 'Imperial County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency. Local "Yellow Health Card" program (currently suspended for renewal).',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Imperial County Environmental Health',
      phone: '(442) 265-1888',
      website: 'https://www.icphd.org/environmental-health/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Local "Yellow Health Card" program (currently suspended for renewal)',
      'Border region considerations for imported food products from Mexico',
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-san-benito',
    name: 'San Benito County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'San Benito County Environmental Health',
      phone: '(831) 637-5367',
      website: 'https://hhsa.cosb.us/environmental-health/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-mariposa',
    name: 'Mariposa County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency. National Park Service additional requirements for Yosemite-area food facilities.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Mariposa County Health Department',
      phone: '(209) 966-3689',
      website: 'https://www.mariposacounty.org/92/Health-Department',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'National Park Service (NPS) additional requirements for Yosemite-area food facilities',
      'Concession-specific food safety requirements for NPS operations',
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-tulare',
    name: 'Tulare County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Tulare County Environmental Health Services',
      phone: '(559) 624-7400',
      website: 'https://tularehhsa.org/environmental-health/',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-kings',
    name: 'Kings County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Kings County Environmental Health Services',
      phone: '(559) 584-1411',
      website: 'https://www.countyofkings.com/departments/community-health-agency/health-division/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-madera',
    name: 'Madera County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'medium',
    healthDepartment: {
      name: 'Madera County Environmental Health',
      phone: '(559) 675-7823',
      website: 'https://www.maderacounty.com/government/public-health/environmental-health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-san-joaquin',
    name: 'San Joaquin County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'large',
    healthDepartment: {
      name: 'San Joaquin County Environmental Health',
      phone: '(209) 468-3420',
      website: 'https://www.sjgov.org/department/envhealth',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-tuolumne',
    name: 'Tuolumne County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Tuolumne County Environmental Health',
      phone: '(209) 533-5633',
      website: 'https://www.tuolumnecounty.ca.gov/155/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },

  {
    id: 'county-calaveras',
    name: 'Calaveras County',
    level: 'county',
    parentId: 'state-ca',
    temperatureThresholds: [],
    cookingTemps: [],
    coolingRequirements: [],
    certifications: [],
    requiredDocuments: [],
    requiredPostings: [],
    serviceFrequencies: [],
    inspectionSystem: {
      type: 'standard',
      details: 'Standard CalCode enforcement with risk-based inspection frequency.',
    },
    populationTier: 'small',
    healthDepartment: {
      name: 'Calaveras County Environmental Health',
      phone: '(209) 754-6399',
      website: 'https://www.calaverasgov.us/Departments/Environmental-Health',
      inspectionFrequency: 'Risk-based: high risk annually, moderate every 18 months',
      permitRenewal: 'Annual',
    },
    specialRequirements: [
      'Standard CalCode enforcement',
    ],
  },
];
