// ============================================================================
// Kitchen Checkup PDF Report Generator — CHECKUP-1
// Generates a branded 2-page PDF: "Where You Stand" + "What This Means"
// ============================================================================

import { jsPDF } from 'jspdf';
import type { CheckupScores } from './checkupScoring';
import { gradeColor, scoreBarColor, formatDollars } from './checkupScoring';

const GOLD = '#A08C5A';
const NAVY = '#1E2D4D';
const GRAY = '#6B7F96';
const LIGHT_GRAY = '#E5E7EB';

const PAGE_W = 210; // A4 mm
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

function hex(h: string): [number, number, number] {
  return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
}

function drawBar(doc: jsPDF, x: number, y: number, w: number, h: number, score: number, label: string) {
  const color = scoreBarColor(score);
  doc.setFillColor(...hex(LIGHT_GRAY));
  doc.roundedRect(x, y, w, h, 2, 2, 'F');
  const barW = Math.max(2, (score / 100) * w);
  doc.setFillColor(...hex(color));
  doc.roundedRect(x, y, barW, h, 2, 2, 'F');
  doc.setFontSize(9);
  doc.setTextColor(...hex(NAVY));
  doc.text(label, x, y - 2);
  doc.setTextColor(...hex(color));
  doc.text(`${score}/100`, x + w + 3, y + h - 1);
}

function drawHeaderBand(doc: jsPDF, height: number) {
  doc.setFillColor(...hex(NAVY));
  doc.rect(0, 0, PAGE_W, height, 'F');
  // Logo
  doc.setFontSize(18);
  doc.setTextColor(...hex(GOLD));
  doc.text('Evid', MARGIN, 14);
  doc.setTextColor(255, 255, 255);
  doc.text('LY', MARGIN + 18, 14);
}

function drawFooter(doc: jsPDF, page: number, totalPages: number) {
  doc.setFontSize(6);
  doc.setTextColor(...hex(GRAY));
  const disc = [
    'This checkup is for informational purposes only and does not constitute legal, insurance, or regulatory advice.',
    'Estimates are approximations based on industry averages and your self-reported answers.',
  ];
  doc.text(disc[0], MARGIN, 273);
  doc.text(disc[1], MARGIN, 276);

  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Generated by EvidLY · www.getevidly.com · ${now}`, MARGIN, 280);
  doc.text('Questions? Contact Arthur Haggerty · arthur@getevidly.com · (209)636-6116', MARGIN, 283);
  doc.text(`Page ${page} of ${totalPages}`, PAGE_W - MARGIN, 283, { align: 'right' });
}

export interface CheckupLeadData {
  businessName: string;
  contactName: string;
  email: string;
  city: string;
  zipCode: string;
  jurisdiction?: string;
}

export function generateCheckupPdf(lead: CheckupLeadData, scores: CheckupScores): jsPDF {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // ── PAGE 1: WHERE YOU STAND ────────────────────────────────────────────────

  drawHeaderBand(doc, 30);
  doc.setFontSize(10);
  doc.setTextColor(200, 200, 200);
  doc.text('Kitchen Checkup Report', MARGIN, 24);
  doc.setFontSize(8);
  doc.text(now, PAGE_W - MARGIN, 14, { align: 'right' });

  let y = 38;

  // Business info
  doc.setFontSize(14);
  doc.setTextColor(...hex(NAVY));
  doc.text(lead.businessName, MARGIN, y);
  y += 5;
  doc.setFontSize(9);
  doc.setTextColor(...hex(GRAY));
  doc.text(`Prepared for ${lead.contactName} | ${lead.email}`, MARGIN, y);
  if (lead.city || lead.zipCode) {
    y += 4;
    doc.text([lead.city, lead.zipCode].filter(Boolean).join(', '), MARGIN, y);
  }
  y += 10;

  // Overall Grade
  doc.setFontSize(10);
  doc.setTextColor(...hex(GOLD));
  doc.text('OVERALL GRADE', MARGIN, y);
  y += 3;

  const gc = gradeColor(scores.overallGrade);
  doc.setFillColor(...hex(gc));
  doc.roundedRect(MARGIN, y, 28, 18, 4, 4, 'F');
  doc.setFontSize(26);
  doc.setTextColor(255, 255, 255);
  doc.text(scores.overallGrade, MARGIN + 14, y + 13, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(...hex(gc));
  doc.text(scores.gradeLabel, MARGIN + 33, y + 8);

  doc.setFontSize(7);
  doc.setTextColor(...hex(GRAY));
  doc.text('Based on average of four business impact areas', MARGIN + 33, y + 13);

  y += 25;

  // Category Scores
  doc.setFontSize(10);
  doc.setTextColor(...hex(GOLD));
  doc.text('CATEGORY SCORES', MARGIN, y);
  y += 8;

  drawBar(doc, MARGIN, y, CONTENT_W - 28, 4, scores.facilitySafety, 'Your Kitchen & Equipment');
  y += 13;
  drawBar(doc, MARGIN, y, CONTENT_W - 28, 4, scores.foodSafety, 'Day-to-Day Operations');
  y += 13;
  drawBar(doc, MARGIN, y, CONTENT_W - 28, 4, scores.documentation, 'Paperwork & Records');
  y += 12;

  // Findings
  doc.setFontSize(10);
  doc.setTextColor(...hex(GOLD));
  doc.text("HERE'S WHAT WE FOUND", MARGIN, y);
  y += 5;

  doc.setFontSize(7.5);
  const gapFindings = scores.findings.filter((f) => !f.isPositive);
  const positiveFindings = scores.findings.filter((f) => f.isPositive);

  for (const f of gapFindings.slice(0, 10)) {
    if (y > 252) break;
    const sColor = f.severity === 'critical' ? '#ef4444' : f.severity === 'high' ? '#f97316' : f.severity === 'medium' ? '#eab308' : '#94a3b8';
    doc.setFillColor(...hex(sColor));
    doc.circle(MARGIN + 2, y, 1.2, 'F');
    doc.setTextColor(...hex(NAVY));
    const lines = doc.splitTextToSize(f.description, CONTENT_W - 8);
    doc.text(lines, MARGIN + 6, y + 1);
    y += lines.length * 3.2 + 1.5;
  }

  if (positiveFindings.length > 0 && y < 248) {
    y += 2;
    for (const f of positiveFindings.slice(0, 4)) {
      if (y > 255) break;
      doc.setFillColor(...hex('#22c55e'));
      doc.circle(MARGIN + 2, y, 1.2, 'F');
      doc.setTextColor(...hex('#22c55e'));
      const lines = doc.splitTextToSize(f.description, CONTENT_W - 8);
      doc.text(lines, MARGIN + 6, y + 1);
      y += lines.length * 3.2 + 1.5;
    }
  }

  // Jurisdiction context
  if (lead.jurisdiction && y < 255) {
    y += 3;
    doc.setFontSize(7);
    doc.setTextColor(...hex(GRAY));
    const jLines = doc.splitTextToSize(lead.jurisdiction, CONTENT_W);
    doc.text(jLines, MARGIN, y);
  }

  drawFooter(doc, 1, 2);

  // ── PAGE 2: WHAT THIS MEANS FOR YOUR BUSINESS ──────────────────────────────

  doc.addPage();
  drawHeaderBand(doc, 25);
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text('What This Means for Your Business', MARGIN, 17);

  y = 32;

  doc.setFontSize(7);
  doc.setTextColor(...hex(GRAY));
  doc.text('These are the same four areas your EvidLY dashboard covers — so you always know where you stand.', MARGIN, y);
  y += 6;

  // 4 Impact Areas
  const areas = [
    { label: 'Business Continuity', score: scores.revenueRisk, est: `${formatDollars(scores.estimates.revenueRiskLow)} – ${formatDollars(scores.estimates.revenueRiskHigh)}/yr`, drivers: scores.riskDrivers.revenue || [] },
    { label: 'Exposure', score: scores.liabilityRisk, est: `${formatDollars(scores.estimates.liabilityRiskLow)} – ${formatDollars(scores.estimates.liabilityRiskHigh)} potential`, drivers: scores.riskDrivers.liability || [] },
    { label: 'Avoidable Costs', score: scores.costRisk, est: `${formatDollars(scores.estimates.avoidableCosts)} – ${formatDollars(scores.estimates.avoidableCostsHigh)}/yr`, drivers: scores.riskDrivers.cost || [] },
    { label: 'Day-to-Day Impact', score: scores.operationalRisk, est: `~${scores.estimates.operationalDays} days disruption/yr`, drivers: scores.riskDrivers.operational || [] },
  ];

  for (const area of areas) {
    doc.setFontSize(10);
    doc.setTextColor(...hex(NAVY));
    doc.text(area.label, MARGIN, y);
    const sc = scoreBarColor(area.score);
    doc.setTextColor(...hex(sc));
    doc.text(`${area.score}/100`, PAGE_W - MARGIN, y, { align: 'right' });
    y += 4;

    // Bar
    doc.setFillColor(...hex(LIGHT_GRAY));
    doc.roundedRect(MARGIN, y, CONTENT_W, 3.5, 1, 1, 'F');
    const bw = Math.max(1, (area.score / 100) * CONTENT_W);
    doc.setFillColor(...hex(sc));
    doc.roundedRect(MARGIN, y, bw, 3.5, 1, 1, 'F');
    y += 5;

    // Estimate
    doc.setFontSize(7.5);
    doc.setTextColor(...hex(GOLD));
    doc.text(`Estimated: ${area.est}`, MARGIN + 2, y);
    y += 3.5;

    // Drivers
    doc.setFontSize(7);
    doc.setTextColor(...hex(GRAY));
    for (const d of area.drivers.slice(0, 3)) {
      const lines = doc.splitTextToSize(`• ${d.title} — ${d.description}`, CONTENT_W - 6);
      doc.text(lines, MARGIN + 3, y);
      y += lines.length * 3 + 0.5;
    }
    y += 4;
  }

  // Total Estimated Impact
  if (y < 220) {
    doc.setFillColor(...hex('#FEF3C7'));
    doc.roundedRect(MARGIN, y, CONTENT_W, 16, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...hex(NAVY));
    doc.text('TOTAL ESTIMATED ANNUAL IMPACT', MARGIN + 4, y + 5);
    doc.setFontSize(12);
    doc.setTextColor(...hex('#92400e'));
    doc.text(`${formatDollars(scores.estimates.totalLow)} – ${formatDollars(scores.estimates.totalHigh)}`, MARGIN + 4, y + 12);
    doc.setFontSize(6);
    doc.setTextColor(...hex(GRAY));
    doc.text('Estimated — these are directional, not exact', MARGIN + CONTENT_W - 2, y + 12, { align: 'right' });
    y += 22;
  }

  // Recommendations
  if (y < 240) {
    doc.setFontSize(9);
    doc.setTextColor(...hex(GOLD));
    doc.text('RECOMMENDATIONS', MARGIN, y);
    y += 5;

    const hasFacilityGaps = scores.facilitySafety > 20;
    const hasOpsGaps = scores.foodSafety > 20 || scores.documentation > 20;

    doc.setFontSize(7.5);

    if (hasFacilityGaps && y < 250) {
      doc.setTextColor(...hex(NAVY));
      doc.text('Cleaning Pros Plus can help with:', MARGIN, y);
      y += 3.5;
      doc.setTextColor(...hex(GRAY));
      doc.text('• Hood cleaning service (scheduled per your cooking type)', MARGIN + 3, y); y += 3;
      doc.text('• Fire suppression inspection', MARGIN + 3, y); y += 3;
      doc.text('• Fire extinguisher inspection/recharging', MARGIN + 3, y); y += 3;
      doc.text('Contact: arthur@cleaningprosplus.com | (209) 636-6116', MARGIN + 3, y); y += 5;
    }

    if (hasOpsGaps && y < 258) {
      doc.setTextColor(...hex(NAVY));
      doc.text('EvidLY can help with:', MARGIN, y);
      y += 3.5;
      doc.setTextColor(...hex(GRAY));
      doc.text('• Dashboard showing where everything stands, updated as things happen', MARGIN + 3, y); y += 3;
      doc.text('• Reminders before things come due', MARGIN + 3, y); y += 3;
      doc.text('• All vendor documents in one place', MARGIN + 3, y); y += 3;
      doc.text('• Digital temperature logging & HACCP management', MARGIN + 3, y); y += 3;
      doc.text('Start free: www.getevidly.com/signup — $99/month', MARGIN + 3, y);
    }
  }

  drawFooter(doc, 2, 2);

  return doc;
}
