// ── Branded PDF Export Utilities for Reports Module ──────────────────────
// Uses jsPDF (already installed). Follows assessmentPdf.ts patterns.

import { jsPDF } from 'jspdf';

const GOLD = '#A08C5A';
const NAVY = '#1E2D4D';
const GRAY = '#6B7F96';
const LIGHT_GRAY = '#E5E7EB';
const WHITE = '#FFFFFF';
const ROW_ALT = '#F8F9FC';

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

function hexToRgb(hex: string): [number, number, number] {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

// ── Header Band ────────────────────────────────────────────────────────
export function drawReportHeader(
  doc: jsPDF,
  title: string,
  subtitle: string,
  locationName: string,
  dateRange: string,
): number {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Navy header band
  doc.setFillColor(...hexToRgb(NAVY));
  doc.rect(0, 0, PAGE_W, 38, 'F');

  // EvidLY logo
  doc.setFontSize(20);
  doc.setTextColor(...hexToRgb(GOLD));
  doc.text('E', MARGIN, 18);
  doc.setTextColor(255, 255, 255);
  doc.text('vid', MARGIN + 8, 18);
  doc.setTextColor(...hexToRgb(GOLD));
  doc.text('LY', MARGIN + 22, 18);

  // Report title
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(title, MARGIN, 30);

  // Date + location (right side)
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  doc.text(now, PAGE_W - MARGIN, 14, { align: 'right' });
  doc.text(`${locationName} · ${dateRange}`, PAGE_W - MARGIN, 22, { align: 'right' });

  // Gold divider line
  doc.setDrawColor(...hexToRgb(GOLD));
  doc.setLineWidth(0.5);
  doc.line(MARGIN, 39, PAGE_W - MARGIN, 39);

  // Subtitle
  doc.setFontSize(9);
  doc.setTextColor(...hexToRgb(GRAY));
  doc.text(subtitle, MARGIN, 46);

  return 52;
}

// ── Footer ─────────────────────────────────────────────────────────────
export function drawPageFooter(doc: jsPDF, pageNum: number, totalPages: number): void {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFontSize(7);
  doc.setTextColor(...hexToRgb(GRAY));
  doc.text(
    `Generated by EvidLY · www.getevidly.com · ${now}`,
    MARGIN,
    PAGE_H - 12,
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, PAGE_H - 12, { align: 'right' });

  // Disclaimer
  doc.setFontSize(6);
  doc.text(
    'This report reflects data entered into the EvidLY platform as of the generation date. It does not constitute legal, insurance, or regulatory advice.',
    MARGIN,
    PAGE_H - 8,
  );
}

// ── Table Helper ───────────────────────────────────────────────────────
export function drawTable(
  doc: jsPDF,
  headers: string[],
  rows: string[][],
  startY: number,
  options?: { colWidths?: number[]; fontSize?: number },
): number {
  const fontSize = options?.fontSize || 8;
  const rowH = 7;
  const colCount = headers.length;
  const defaultColW = CONTENT_W / colCount;
  const colWidths = options?.colWidths || headers.map(() => defaultColW);

  let y = startY;

  const checkPageBreak = () => {
    if (y + rowH > PAGE_H - 20) {
      doc.addPage();
      y = MARGIN;
      // Re-draw header row on new page
      doc.setFillColor(...hexToRgb(NAVY));
      doc.rect(MARGIN, y, CONTENT_W, rowH, 'F');
      doc.setFontSize(fontSize);
      doc.setTextColor(255, 255, 255);
      let hx = MARGIN + 2;
      headers.forEach((h, i) => {
        doc.text(h, hx, y + 5);
        hx += colWidths[i];
      });
      y += rowH;
    }
  };

  // Header row
  doc.setFillColor(...hexToRgb(NAVY));
  doc.rect(MARGIN, y, CONTENT_W, rowH, 'F');
  doc.setFontSize(fontSize);
  doc.setTextColor(255, 255, 255);
  let hx = MARGIN + 2;
  headers.forEach((h, i) => {
    doc.text(h, hx, y + 5);
    hx += colWidths[i];
  });
  y += rowH;

  // Data rows
  rows.forEach((row, rowIdx) => {
    checkPageBreak();
    const bg = rowIdx % 2 === 0 ? WHITE : ROW_ALT;
    doc.setFillColor(...hexToRgb(bg));
    doc.rect(MARGIN, y, CONTENT_W, rowH, 'F');
    doc.setFontSize(fontSize);
    doc.setTextColor(...hexToRgb(NAVY));
    let rx = MARGIN + 2;
    row.forEach((cell, i) => {
      const maxW = colWidths[i] - 4;
      const truncated = doc.getTextWidth(cell) > maxW
        ? cell.substring(0, Math.floor(cell.length * (maxW / doc.getTextWidth(cell)))) + '…'
        : cell;
      doc.text(truncated, rx, y + 5);
      rx += colWidths[i];
    });
    y += rowH;
  });

  return y + 4;
}

// ── Section Heading ────────────────────────────────────────────────────
export function drawSectionHeading(doc: jsPDF, title: string, y: number): number {
  if (y + 14 > PAGE_H - 20) {
    doc.addPage();
    y = MARGIN;
  }
  doc.setFontSize(11);
  doc.setTextColor(...hexToRgb(NAVY));
  doc.text(title, MARGIN, y + 4);

  // Gold underline
  doc.setDrawColor(...hexToRgb(GOLD));
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 6, MARGIN + doc.getTextWidth(title) + 2, y + 6);

  return y + 12;
}

// ── Score Badge ────────────────────────────────────────────────────────
export function drawScoreBadge(
  doc: jsPDF,
  x: number,
  y: number,
  score: number,
  label: string,
): void {
  const color = score >= 80 ? '#16a34a' : score >= 60 ? '#d97706' : '#dc2626';

  doc.setFontSize(22);
  doc.setTextColor(...hexToRgb(color));
  doc.text(String(score), x, y);

  doc.setFontSize(8);
  doc.setTextColor(...hexToRgb(GRAY));
  doc.text(label, x, y + 6);
}

// ── Horizontal Bar ─────────────────────────────────────────────────────
export function drawHorizontalBar(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  score: number,
  label: string,
): void {
  const color = score >= 80 ? '#16a34a' : score >= 60 ? '#d97706' : '#dc2626';

  // Background
  doc.setFillColor(...hexToRgb(LIGHT_GRAY));
  doc.roundedRect(x, y, w, h, 1, 1, 'F');

  // Score bar
  const barW = Math.max(1, (score / 100) * w);
  doc.setFillColor(...hexToRgb(color));
  doc.roundedRect(x, y, barW, h, 1, 1, 'F');

  // Label
  doc.setFontSize(8);
  doc.setTextColor(...hexToRgb(NAVY));
  doc.text(label, x, y - 2);

  // Score text
  doc.setTextColor(...hexToRgb(color));
  doc.text(`${score}%`, x + w + 3, y + h - 1);
}

// ── Stat Box ───────────────────────────────────────────────────────────
export function drawStatBox(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  value: string,
  label: string,
): void {
  doc.setFillColor(...hexToRgb('#F4F6FA'));
  doc.roundedRect(x, y, w, 18, 2, 2, 'F');

  doc.setFontSize(14);
  doc.setTextColor(...hexToRgb(NAVY));
  doc.text(value, x + w / 2, y + 8, { align: 'center' });

  doc.setFontSize(7);
  doc.setTextColor(...hexToRgb(GRAY));
  doc.text(label, x + w / 2, y + 14, { align: 'center' });
}

// ── Create & Save PDF ──────────────────────────────────────────────────
export function createReportPdf(): jsPDF {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
}

export function saveReportPdf(doc: jsPDF, filename: string): void {
  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPageFooter(doc, i, totalPages);
  }
  doc.save(filename);
}

export { MARGIN, CONTENT_W, PAGE_W, PAGE_H, GOLD, NAVY, GRAY, hexToRgb };
