import type { BISignal } from './types';

export const DEMO_SIGNALS: BISignal[] = [
  {
    id: 'demo-bi-1',
    title: 'Merced County prioritizing cold-holding enforcement',
    summary: 'Your Airport location operates in Merced County, which has elevated cold-holding temperature compliance to priority enforcement following an outbreak investigation. Digital probe verification is now standard.',
    category: 'food_safety',
    signal_type: 'enforcement_priority',
    source_name: 'Merced County EHD',
    priority: 'critical',
    county: 'Merced County',
    published_at: new Date(Date.now() - 86400000).toISOString(),
    risk_revenue: 'high',
    risk_liability: 'critical',
    risk_cost: 'low',
    risk_operational: 'critical',
    workforce_risk_level: null,
    client_impact_revenue: 'Grade card at risk if cold-holding violations found during semi-annual inspection',
    client_impact_liability: 'Direct liability — post-outbreak enforcement targets cold-holding non-compliance',
    client_impact_cost: 'No new equipment needed — process and protocol change only',
    client_impact_operational: 'Immediate cold-holding protocol update required across Airport location',
    client_impact_workforce: null,
    recommended_action: 'Audit all cold-holding units at Airport location. Verify digital probe calibration records. Update cold-holding SOPs.',
    action_deadline: '2026-03-15',
    relevance_reason: 'Your Airport location in Merced County is directly affected by the enforcement priority.',
    feed_type: 'jurisdiction',
  },
  {
    id: 'demo-bi-2',
    title: 'Fresno County inspection frequency increasing',
    summary: 'Downtown location: routine inspections moving from annual to semi-annual for high-risk facilities starting April 2026.',
    category: 'regulatory',
    signal_type: 'inspection_frequency',
    source_name: 'Fresno County EHD',
    priority: 'high',
    county: 'Fresno County',
    published_at: new Date(Date.now() - 172800000).toISOString(),
    risk_revenue: 'high',
    risk_liability: 'medium',
    risk_cost: 'low',
    risk_operational: 'high',
    workforce_risk_level: 'medium',
    client_impact_revenue: 'More frequent inspections increase grade card risk exposure',
    client_impact_liability: 'Repeat violations during semi-annual cycle trigger mandatory re-inspection',
    client_impact_cost: 'Minimal — no new equipment or infrastructure required',
    client_impact_operational: 'All open corrective actions must be resolved before next cycle',
    client_impact_workforce: 'Staff must be trained on updated inspection readiness protocols',
    recommended_action: 'Resolve all open corrective actions at Downtown. Schedule pre-inspection internal audit.',
    action_deadline: '2026-04-01',
    relevance_reason: 'Your Downtown location in Fresno County — semi-annual cycle starts April 2026.',
    feed_type: 'jurisdiction',
  },
  {
    id: 'demo-bi-3',
    title: 'Stanislaus DER adds allergen management scoring',
    summary: 'University location will be scored on food allergen management. Written protocols and staff training records required.',
    category: 'food_safety',
    signal_type: 'methodology_change',
    source_name: 'Stanislaus County DER',
    priority: 'high',
    county: 'Stanislaus County',
    published_at: new Date(Date.now() - 43200000).toISOString(),
    risk_revenue: 'medium',
    risk_liability: 'critical',
    risk_cost: 'low',
    risk_operational: 'high',
    workforce_risk_level: 'high',
    client_impact_revenue: 'New scoring category could lower overall inspection grade',
    client_impact_liability: 'Allergen failure classified as immediate critical violation',
    client_impact_cost: 'Minimal — documentation and training costs only',
    client_impact_operational: 'Written allergen management protocol and staff training required before effective date',
    client_impact_workforce: 'All food-handling staff require documented allergen awareness training',
    recommended_action: 'Develop written allergen management protocol. Schedule allergen awareness training for all food-handling staff.',
    action_deadline: '2026-03-31',
    relevance_reason: 'Your University location in Stanislaus County — new scoring effective March 2026.',
    feed_type: 'jurisdiction',
  },
  {
    id: 'demo-bi-4',
    title: 'Annual hood suppression testing now required',
    summary: 'Stanislaus County Fire: annual UL-300 compliance testing required (was biennial). University location must schedule before April 15.',
    category: 'facility_safety',
    signal_type: 'fire_code_update',
    source_name: 'Stanislaus County Fire',
    priority: 'high',
    county: 'Stanislaus County',
    published_at: new Date(Date.now() - 21600000).toISOString(),
    risk_revenue: null,
    risk_liability: 'high',
    risk_cost: 'high',
    risk_operational: 'medium',
    workforce_risk_level: null,
    client_impact_revenue: null,
    client_impact_liability: 'Fire code violation triggers Notice of Violation from fire AHJ',
    client_impact_cost: 'UL-300 suppression test costs $400-$800 annually',
    client_impact_operational: 'Must schedule certified technician before deadline',
    client_impact_workforce: null,
    recommended_action: 'Schedule UL-300 suppression test at University location before April 15. Contact certified fire suppression vendor.',
    action_deadline: '2026-04-15',
    relevance_reason: 'Your University location in Stanislaus County — annual testing now mandatory.',
    feed_type: 'jurisdiction',
  },
  {
    id: 'demo-bi-5',
    title: 'FDA Class I recall: frozen produce contamination',
    summary: 'Multiple frozen vegetable products recalled due to potential Listeria monocytogenes contamination. Check supplier and lot codes.',
    category: 'recall',
    signal_type: 'fda_recall',
    source_name: 'FDA Enforcement Reports',
    priority: 'critical',
    county: 'Statewide',
    published_at: new Date(Date.now() - 7200000).toISOString(),
    risk_revenue: 'medium',
    risk_liability: 'critical',
    risk_cost: 'medium',
    risk_operational: 'high',
    workforce_risk_level: 'low',
    client_impact_revenue: 'Menu disruption if affected products are in current inventory',
    client_impact_liability: 'Serving recalled product creates direct foodborne illness liability',
    client_impact_cost: 'Product disposal costs plus emergency procurement of replacements',
    client_impact_operational: 'Immediate inventory check required across all locations',
    client_impact_workforce: 'Staff must be briefed on affected products and receiving inspection procedures',
    recommended_action: 'Check all frozen vegetable inventory against recalled lot codes. Pull and quarantine any matches. Brief receiving staff.',
    action_deadline: null,
    relevance_reason: 'Statewide recall — all 3 locations potentially affected.',
    feed_type: 'recall',
  },
  {
    id: 'demo-bi-6',
    title: 'California SB 1234: Updated food handler certification requirements',
    summary: 'New state legislation requires biennial food handler recertification (was 3-year cycle). Effective January 2027 with 6-month grace period.',
    category: 'regulatory',
    signal_type: 'legislative',
    source_name: 'California Legislature',
    priority: 'normal',
    county: 'Statewide',
    published_at: new Date(Date.now() - 604800000).toISOString(),
    risk_revenue: 'low',
    risk_liability: 'medium',
    risk_cost: 'medium',
    risk_operational: 'medium',
    workforce_risk_level: 'high',
    client_impact_revenue: 'Non-compliance could result in permit suspension',
    client_impact_liability: 'Operating with non-certified handlers increases liability exposure',
    client_impact_cost: 'Additional certification costs for biennial renewal cycle',
    client_impact_operational: 'Training scheduling impact across all locations',
    client_impact_workforce: 'All food handlers must renew certifications on 2-year cycle starting Jan 2027',
    recommended_action: 'Audit current food handler certification dates. Build renewal calendar for biennial compliance. Budget for increased certification costs.',
    action_deadline: '2027-01-01',
    relevance_reason: 'Statewide legislation — affects all 3 locations and all food-handling staff.',
    feed_type: 'legislative',
  },
];
