/**
 * BulkQRPrintModal — Select multiple equipment and generate bulk QR print PDF.
 */
import { useState, useMemo } from 'react';
import { X, Printer, QrCode, Search, CheckSquare } from 'lucide-react';
import DOMPurify from 'dompurify';
import type { EquipmentItem } from '../../hooks/api/useEquipment';
import { NAVY, CARD_BG, CARD_BORDER, TEXT_TERTIARY, MUTED } from '../dashboard/shared/constants';
import { Modal } from '../ui/Modal';

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
}

interface BulkQRPrintModalProps {
  items: EquipmentItem[];
  onClose: () => void;
}

export function BulkQRPrintModal({ items, onClose }: BulkQRPrintModalProps) {
  const [selected, setSelected] = useState<Set<string>>(new Set(items.map(e => e.id)));
  const [search, setSearch] = useState('');
  const [layout, setLayout] = useState<'labels' | 'list'>('labels');

  const filtered = useMemo(() => {
    if (!search.trim()) return items;
    const q = search.toLowerCase();
    return items.filter(e => e.name.toLowerCase().includes(q) || e.locationName.toLowerCase().includes(q));
  }, [items, search]);

  const toggleItem = (id: string) => {
    const next = new Set(selected);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setSelected(next);
  };

  const toggleAll = () => {
    if (selected.size === filtered.length) setSelected(new Set());
    else setSelected(new Set(filtered.map(e => e.id)));
  };

  const handlePrint = () => {
    const selectedItems = items.filter(e => selected.has(e.id));
    if (selectedItems.length === 0) return;

    const printWin = window.open('', '_blank', 'width=800,height=1000');
    if (!printWin) return;

    const labelsHtml = selectedItems.map(e => `
      <div style="display:inline-block;width:${layout === 'labels' ? '30%' : '100%'};padding:12px;margin:4px;border:1px solid #ddd;border-radius:6px;text-align:center;page-break-inside:avoid;">
        <div id="qr-${e.id}" style="margin:0 auto 6px;"></div>
        <p style="font-size:10px;font-weight:bold;color:#1E2D4D;margin:0;">${escapeHtml(e.name)}</p>
        <p style="font-size:8px;color:#6B7F96;margin:2px 0 0;">${escapeHtml(e.locationName)}</p>
        <p style="font-size:7px;font-family:monospace;color:#9CA3AF;margin:2px 0 0;">${e.qrCodeId}</p>
      </div>
    `).join('');

    const qrScripts = selectedItems.map(e => `
      new QRCode(document.getElementById('qr-${e.id}'), {
        text: "${window.location.origin}/equipment/scan/${e.qrCodeId}",
        width: ${layout === 'labels' ? 80 : 120},
        height: ${layout === 'labels' ? 80 : 120},
        correctLevel: QRCode.CorrectLevel.M
      });
    `).join('\n');

    printWin.document.write(DOMPurify.sanitize(`
      <!DOCTYPE html>
      <html><head><title>Bulk QR Codes - HoodOps</title>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"><\/script>
      <style>
        body { font-family: sans-serif; padding: 20px; }
        @media print { body { padding: 10px; } }
      </style>
      </head><body>
      <h2 style="color:#1E2D4D;margin-bottom:4px;">Equipment QR Codes</h2>
      <p style="color:#6B7F96;font-size:12px;margin-bottom:16px;">${selectedItems.length} labels &middot; Generated by HoodOps</p>
      <div style="${layout === 'labels' ? 'display:flex;flex-wrap:wrap;gap:4px;' : ''}">${labelsHtml}</div>
      <script>${qrScripts}
        setTimeout(function() { window.print(); window.close(); }, 800);
      <\/script>
      </body></html>
    `, { WHOLE_DOCUMENT: true, ADD_TAGS: ['style', 'script'], ADD_ATTR: ['src', 'class', 'style', 'id'] }));
    printWin.document.close();
  };

  return (
    <Modal isOpen={true} onClose={onClose} size="lg" className="max-h-[85vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b flex-shrink-0" style={{ borderColor: CARD_BORDER }}>
          <div className="flex items-center gap-2">
            <QrCode className="w-5 h-5" style={{ color: '#1E2D4D' }} />
            <h2 className="text-base font-bold" style={{ color: NAVY }}>Print QR Codes</h2>
          </div>
          <button onClick={onClose} className="p-2.5 -m-1 rounded hover:bg-[#1E2D4D]/5" aria-label="Close"><X className="w-5 h-5" style={{ color: TEXT_TERTIARY }} /></button>
        </div>

        <div className="p-5 space-y-4 overflow-y-auto flex-1">
          {/* Search */}
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{ color: TEXT_TERTIARY }} />
            <input
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search equipment..."
              className="w-full pl-9 pr-3 py-2 text-sm rounded-xl border"
              style={{ borderColor: CARD_BORDER, color: NAVY }}
            />
          </div>

          {/* Select all */}
          <div className="flex items-center justify-between">
            <button onClick={toggleAll} className="flex items-center gap-1.5 text-xs font-medium" style={{ color: '#1E2D4D' }}>
              <CheckSquare className="w-3.5 h-3.5" />
              {selected.size === filtered.length ? 'Deselect All' : 'Select All'}
            </button>
            <span className="text-xs" style={{ color: TEXT_TERTIARY }}>{selected.size} selected</span>
          </div>

          {/* Equipment list */}
          <div className="space-y-1 max-h-[300px] overflow-y-auto">
            {filtered.map(e => (
              <label
                key={e.id}
                className="flex items-center gap-3 p-2 rounded-lg cursor-pointer hover:bg-[#FAF7F0] transition-colors"
              >
                <input
                  type="checkbox"
                  checked={selected.has(e.id)}
                  onChange={() => toggleItem(e.id)}
                  style={{ accentColor: '#1E2D4D' }}
                />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium truncate" style={{ color: NAVY }}>{e.name}</p>
                  <p className="text-xs truncate" style={{ color: TEXT_TERTIARY }}>{e.locationName}</p>
                </div>
                <span className="text-xs font-mono" style={{ color: TEXT_TERTIARY }}>{e.qrCodeId}</span>
              </label>
            ))}
          </div>

          {/* Layout */}
          <div>
            <label className="block text-xs font-semibold mb-2" style={{ color: MUTED }}>Print Layout</label>
            <div className="grid grid-cols-2 gap-2">
              <button
                onClick={() => setLayout('labels')}
                className="p-3 rounded-xl border text-left"
                style={{ borderColor: layout === 'labels' ? '#1E2D4D' : CARD_BORDER, background: layout === 'labels' ? '#eef4f8' : CARD_BG }}
              >
                <p className="text-xs font-semibold" style={{ color: NAVY }}>Label Sheet</p>
                <p className="text-xs" style={{ color: TEXT_TERTIARY }}>3 columns, multiple per page</p>
              </button>
              <button
                onClick={() => setLayout('list')}
                className="p-3 rounded-xl border text-left"
                style={{ borderColor: layout === 'list' ? '#1E2D4D' : CARD_BORDER, background: layout === 'list' ? '#eef4f8' : CARD_BG }}
              >
                <p className="text-xs font-semibold" style={{ color: NAVY }}>Full List</p>
                <p className="text-xs" style={{ color: TEXT_TERTIARY }}>One per row, larger codes</p>
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-3 p-5 border-t flex-shrink-0" style={{ borderColor: CARD_BORDER }}>
          <button onClick={onClose} className="px-4 py-2 text-sm font-medium rounded-xl border hover:bg-[#FAF7F0]" style={{ borderColor: CARD_BORDER, color: NAVY }}>
            Cancel
          </button>
          <button
            onClick={handlePrint}
            disabled={selected.size === 0}
            className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white rounded-lg transition-colors"
            style={{ background: selected.size === 0 ? '#9CA3AF' : '#1E2D4D' }}
          >
            <Printer className="w-4 h-4" /> Print {selected.size} QR Code{selected.size !== 1 ? 's' : ''}
          </button>
        </div>
    </Modal>
  );
}
