import React from 'react';

interface Props { data: any }

export const ExportReport: React.FC<Props> = ({ data }) => {
  const handleExport = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `<!DOCTYPE html>
<html>
<head>
  <title>EvidLY Corporate Intelligence Report — ${data.orgName}</title>
  <style>
    body { font-family: system-ui, -apple-system, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1e293b; }
    h1 { font-size: 22px; color: #1e293b; margin-bottom: 4px; }
    h2 { font-size: 16px; color: #334155; margin-top: 28px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
    .subtitle { font-size: 13px; color: #64748b; margin-bottom: 24px; }
    .metric-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin-bottom: 20px; }
    .metric-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; }
    .metric-label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
    .metric-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
    .location-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f1f5f9; }
    .risk-critical { color: #dc2626; } .risk-high { color: #f97316; } .risk-medium { color: #eab308; } .risk-low { color: #22c55e; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Corporate Intelligence Report</h1>
  <p class="subtitle">${data.orgName} — ${data.period} Analysis — Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

  <h2>Organization Overview</h2>
  <div class="metric-grid">
    <div class="metric-box">
      <div class="metric-label">Total Open Items</div>
      <div class="metric-value">${data.orgMetrics.totalOpenItems}</div>
    </div>
    <div class="metric-box">
      <div class="metric-label">Risk Exposure</div>
      <div class="metric-value risk-critical">$${data.orgMetrics.totalEstimatedRiskExposure.toLocaleString()}</div>
    </div>
    <div class="metric-box">
      <div class="metric-label">Compliance Savings</div>
      <div class="metric-value risk-low">$${data.orgMetrics.totalEstimatedSavings.toLocaleString()}</div>
    </div>
  </div>

  <h2>Location Detail</h2>
  ${data.complianceMatrix.map((loc: any) => `
    <div class="location-row">
      <div>
        <strong>${loc.locationName}</strong><br/>
        <span style="font-size:12px;color:#64748b">${loc.jurisdiction} — Food: ${loc.foodSafetyStatus} · Fire: ${loc.fireSafetyVerdict}</span>
      </div>
      <div style="text-align:right">
        <span class="risk-${loc.riskLevel}" style="font-weight:700;text-transform:uppercase;font-size:12px">${loc.riskLevel}</span><br/>
        <span style="font-size:12px;color:#64748b">Exposure: $${loc.estimatedRiskExposure.toLocaleString()}</span>
      </div>
    </div>
  `).join('')}

  <h2>Permits Expiring (Next 30 Days)</h2>
  ${data.complianceMatrix.flatMap((loc: any) => loc.permitExpirations.map((p: any) =>
    `<div class="location-row"><span>${loc.locationName}: ${p.document}</span><span class="${p.daysUntilExpiry <= 7 ? 'risk-critical' : 'risk-high'}" style="font-weight:600">${p.daysUntilExpiry} days</span></div>`
  )).join('') || '<p style="color:#64748b;font-size:13px">No permits expiring in the next 30 days.</p>'}

  <div class="footer">
    Generated by EvidLY Corporate Intelligence · ${new Date().toISOString()}<br/>
    This report contains estimates based on compliance data. Verify all regulatory requirements with your Authority Having Jurisdiction (AHJ).
  </div>
</body>
</html>`;

    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  };

  return (
    <button onClick={handleExport}
      style={{
        background: '#A08C5A', border: 'none', borderRadius: '8px',
        padding: '8px 16px', color: '#ffffff', fontSize: '12px',
        fontWeight: 700, cursor: 'pointer', fontFamily: 'system-ui',
        display: 'flex', alignItems: 'center', gap: '6px',
      }}>
      {'📄'} Export Report
    </button>
  );
};
