/**
 * PredictiveAnalysis — PREDICT-DAY1-01
 *
 * Operator-facing predictions page. Shows location risk ranking,
 * trajectory projections, and multi-dimensional risk grid.
 * All data from useLocationRiskPredictions (REAL data only).
 * Demo mode: empty state, zero fake data.
 */
import { useDemo } from '../contexts/DemoContext';
import { useLocationRiskPredictions } from '../hooks/useLocationRiskPredictions';
import { PredictiveRisk } from '../components/intelligence/PredictiveRisk';
import { RiskRadar } from '../components/intelligence/RiskRadar';

const NAVY = '#1E2D4D';
const GOLD = '#A08C5A';

function riskBadgeStyle(level) {
  const map = {
    critical: { bg: '#FEF2F2', color: '#991B1B', border: '#FECACA' },
    high:     { bg: '#FFF7ED', color: '#9A3412', border: '#FED7AA' },
    moderate: { bg: '#FFFBEB', color: '#92400E', border: '#FDE68A' },
    low:      { bg: '#F0FDF4', color: '#166534', border: '#BBF7D0' },
  };
  return map[level] || map.low;
}

function trajectoryArrow(trajectory) {
  if (trajectory === 'declining') return { symbol: '\u2198', color: '#ef4444', label: 'Declining' };
  if (trajectory === 'improving') return { symbol: '\u2197', color: '#4ade80', label: 'Improving' };
  return { symbol: '\u2192', color: '#fbbf24', label: 'Stable' };
}

function formatDate(iso) {
  if (!iso) return '\u2014';
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export default function PredictiveAnalysis() {
  const { isDemoMode } = useDemo();
  const { predictions, loading } = useLocationRiskPredictions();

  // Demo mode: empty state
  if (isDemoMode) {
    return (
      <div style={{ padding: '32px 24px', maxWidth: 1100, margin: '0 auto' }}>
        <Header />
        <div style={{
          textAlign: 'center', padding: '60px 24px', background: '#FFFFFF',
          border: '1px solid #D1D9E6', borderRadius: 12,
          boxShadow: '0 1px 3px rgba(11,22,40,.06)',
        }}>
          <p style={{ fontSize: 42, margin: '0 0 12px', lineHeight: 1 }}>{'\uD83D\uDD2E'}</p>
          <p style={{ color: '#0B1628', fontSize: 16, fontWeight: 700, margin: '0 0 8px' }}>
            Predictive Analysis
          </p>
          <p style={{ color: '#3D5068', fontSize: 13, margin: '0 0 4px', lineHeight: 1.6 }}>
            Predictive analysis requires live compliance data.
          </p>
          <p style={{ color: '#6B7F96', fontSize: 12, margin: 0, lineHeight: 1.6 }}>
            Risk predictions will appear once your locations begin logging checklists, temperatures, and services.
          </p>
        </div>
        <Disclaimer />
      </div>
    );
  }

  if (loading) {
    return (
      <div style={{ padding: '32px 24px', maxWidth: 1100, margin: '0 auto' }}>
        <Header />
        <div style={{
          textAlign: 'center', padding: '40px 24px', background: '#FFFFFF',
          border: '1px solid #D1D9E6', borderRadius: 12,
        }}>
          <p style={{ color: '#3D5068', fontSize: 13 }}>Loading predictions...</p>
        </div>
      </div>
    );
  }

  const hasPredictions = predictions.length > 0;

  return (
    <div style={{ padding: '32px 24px', maxWidth: 1100, margin: '0 auto' }}>
      <Header />

      {/* Advisory banner */}
      <div style={{
        background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: 10,
        padding: '12px 16px', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 10,
      }}>
        <span className="text-base">{'\u26A0\uFE0F'}</span>
        <p style={{ color: '#92400E', fontSize: 12, margin: 0, lineHeight: 1.5 }}>
          <strong>Advisory Only</strong> — These risk indicators are generated by a rules-based model
          and may suggest areas for review. They do not constitute compliance scores or inspection outcomes.
        </p>
      </div>

      {/* Location Risk Ranking */}
      <div style={{
        background: '#FFFFFF', border: '1px solid #D1D9E6', borderRadius: 12,
        padding: '20px', marginBottom: 20,
        boxShadow: '0 1px 3px rgba(11,22,40,.06), 0 1px 2px rgba(11,22,40,.04)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
          <span className="text-base">{'\uD83D\uDCCA'}</span>
          <h2 style={{ color: '#0B1628', fontSize: 14, fontWeight: 700, margin: 0 }}>
            Location Risk Ranking
          </h2>
          <span style={{
            background: `${GOLD}20`, border: `1px solid ${GOLD}40`, borderRadius: 4,
            padding: '2px 6px', fontSize: 10, color: GOLD, fontWeight: 600, marginLeft: 'auto',
          }}>
            rules-v1
          </span>
        </div>

        {!hasPredictions ? (
          <div style={{ textAlign: 'center', padding: '24px 16px', background: '#EEF1F7', borderRadius: 10, border: '1px solid #D1D9E6' }}>
            <p style={{ color: '#3D5068', fontSize: 12, margin: 0 }}>
              No predictions generated yet. Risk rankings will appear after compliance logs are recorded.
            </p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
              <thead>
                <tr style={{ borderBottom: '2px solid #D1D9E6' }}>
                  {['Location', 'Risk Level', 'Failure %', 'Trend', 'Top Risk Factor', 'Service Due'].map(h => (
                    <th key={h} style={{
                      textAlign: 'left', padding: '8px 12px', color: '#3D5068',
                      fontWeight: 600, fontSize: 10, textTransform: 'uppercase', letterSpacing: 0.5,
                    }}>
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {predictions.map(pred => {
                  const badge = riskBadgeStyle(pred.risk_level);
                  const trend = trajectoryArrow(pred.score_trajectory);
                  return (
                    <tr key={pred.id} style={{ borderBottom: '1px solid #E8EDF5' }}>
                      <td style={{ padding: '10px 12px', color: '#0B1628', fontWeight: 600 }}>
                        {pred.location_name || 'Unknown Location'}
                      </td>
                      <td style={{ padding: '10px 12px' }}>
                        <span style={{
                          display: 'inline-block', padding: '3px 10px', borderRadius: 10,
                          background: badge.bg, color: badge.color, border: `1px solid ${badge.border}`,
                          fontWeight: 700, fontSize: 10, textTransform: 'uppercase',
                        }}>
                          {pred.risk_level}
                        </span>
                      </td>
                      <td style={{ padding: '10px 12px', color: '#0B1628', fontWeight: 700 }}>
                        {Math.round(pred.failure_probability * 100)}%
                      </td>
                      <td style={{ padding: '10px 12px' }}>
                        <span style={{ color: trend.color, fontWeight: 600 }}>
                          {trend.symbol} {trend.label}
                        </span>
                      </td>
                      <td style={{ padding: '10px 12px', color: '#3D5068', maxWidth: 220 }}>
                        {pred.top_risk_reasons?.[0] || '\u2014'}
                      </td>
                      <td style={{ padding: '10px 12px', color: '#3D5068' }}>
                        {formatDate(pred.recommended_service_date)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Predictive Risk Trajectory */}
      <PredictiveRisk predictions={predictions} />

      {/* Multi-Dimensional Risk Radar */}
      <RiskRadar predictions={predictions} />

      <Disclaimer />
    </div>
  );
}

function Header() {
  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
        <h1 style={{ color: '#0B1628', fontSize: 22, fontWeight: 800, margin: 0 }}>
          Predictive Analysis
        </h1>
        <span style={{
          background: `${GOLD}20`, border: `1px solid ${GOLD}40`, borderRadius: 4,
          padding: '2px 8px', fontSize: 10, color: GOLD, fontWeight: 700,
        }}>
          AI MODEL
        </span>
      </div>
      <p style={{ color: '#3D5068', fontSize: 13, margin: 0, lineHeight: 1.6 }}>
        Location risk indicators based on checklist completion, temperature compliance,
        service recency, and open corrective actions.
      </p>
    </div>
  );
}

function Disclaimer() {
  return (
    <div style={{
      marginTop: 24, padding: '14px 16px', background: '#EEF1F7',
      border: '1px solid #D1D9E6', borderRadius: 10,
    }}>
      <p style={{ color: '#6B7F96', fontSize: 11, margin: 0, lineHeight: 1.6, textAlign: 'center' }}>
        These predictions are advisory only. They do not constitute compliance scores,
        inspection outcomes, or regulatory determinations. Risk levels are derived from
        a rules-based heuristic model (rules-v1) and should be used as one input among
        many when making operational decisions.
      </p>
    </div>
  );
}
