export const SAMPLE_DATA = {
  stats: {
    documents: 47,
    logs: 312,
    hours: 86,
    money: 3010,
    documentsTrend: 12,
    logsTrend: 8,
    hoursTrend: 15,
    moneyTrend: 18,
  },
  complianceScore: 76,
  complianceBreakdown: {
    operational: 91,
    equipment: 73,
    documentation: 65,
  },
  locations: [
    {
      id: '1',
      name: 'Downtown Kitchen',
      address: '1245 Fulton Street',
      city: 'Fresno',
      state: 'CA',
      lat: 36.7378,
      lng: -119.7871,
      complianceScore: 92,
      actionItems: 2,
    },
    {
      id: '2',
      name: 'Airport Cafe',
      address: '1636 Macready Drive',
      city: 'Merced',
      state: 'CA',
      lat: 37.2847,
      lng: -120.5139,
      complianceScore: 74,
      actionItems: 5,
    },
    {
      id: '3',
      name: 'University Dining',
      address: '1 University Circle',
      city: 'Modesto',
      state: 'CA',
      lat: 37.6393,
      lng: -120.9969,
      complianceScore: 58,
      actionItems: 8,
    },
  ],
  actionItems: [
    {
      id: '1',
      title: 'Health Permit Renewal Due',
      description: 'Annual health permit expires in 14 days',
      dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'Sarah Chen',
      priority: 'soon' as const,
      link: '/documents',
    },
    {
      id: '2',
      title: 'Temperature Logs Behind Schedule',
      description: 'Airport Cafe missing 3 temperature checks today',
      dueDate: new Date().toISOString(),
      assignedTo: 'Kitchen Staff',
      priority: 'urgent' as const,
      link: '/temp-logs',
    },
    {
      id: '3',
      title: 'Food Handler Certificates Expiring',
      description: '2 team members need to renew certifications',
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'HR Team',
      priority: 'soon' as const,
      link: '/team',
    },
    {
      id: '4',
      title: 'Weekly Deep Clean Checklist',
      description: 'University Dining weekly checklist incomplete',
      dueDate: new Date().toISOString(),
      assignedTo: 'Cleaning Crew',
      priority: 'info' as const,
      link: '/checklists',
    },
    {
      id: '5',
      title: 'Vendor Insurance Update Needed',
      description: 'Sysco Foods insurance certificate expired',
      dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      assignedTo: null,
      priority: 'urgent' as const,
      link: '/vendors',
    },
  ],
  activities: [
    {
      id: '1',
      user: 'Marcus Johnson',
      action: 'logged Walk-in Cooler: 38°F ✓',
      time: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      success: true,
    },
    {
      id: '2',
      user: 'Sarah Chen',
      action: 'completed Opening Checklist for Downtown Kitchen',
      time: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      success: true,
    },
    {
      id: '3',
      user: 'David Park',
      action: 'logged Freezer Unit #2: 15°F ✓',
      time: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      success: true,
    },
    {
      id: '4',
      user: 'Emma Rodriguez',
      action: 'uploaded Food Handler Certificate',
      time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      success: true,
    },
    {
      id: '5',
      user: 'Alex Thompson',
      action: 'logged Hot Hold Cabinet: 127°F ✗',
      time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      success: false,
    },
  ],
  todayProgress: {
    tempChecks: { completed: 6, total: 12 },
    checklists: { completed: 2, total: 4 },
    expiringDocs: 0,
  },
};
