import { useNavigate } from 'react-router-dom';
import { useLocationRiskPredictions } from '../../hooks/useLocationRiskPredictions';

const NAVY = '#1E2D4D';
const GOLD = '#A08C5A';

const RISK_COLORS: Record<string, { bg: string; text: string }> = {
  critical: { bg: '#FEF2F2', text: '#DC2626' },
  high:     { bg: '#FFF7ED', text: '#C2410C' },
  moderate: { bg: '#FFFBEB', text: '#D97706' },
  low:      { bg: '#F0FDF4', text: '#16A34A' },
  unknown:  { bg: '#F3F4F6', text: '#6B7280' },
};

export function PortfolioRiskCard() {
  const navigate = useNavigate();
  const { predictions, loading, highestRisk, riskCounts } = useLocationRiskPredictions();

  // Loading skeleton
  if (loading) {
    return (
      <div className="bg-white rounded-xl overflow-hidden" style={{ border: '1px solid #e5e7eb' }}>
        <div className="px-4 py-3" style={{ borderBottom: '1px solid #f3f4f6' }}>
          <div className="h-4 w-48 rounded" style={{ background: '#E5E7EB', animation: 'pulse 1.5s ease-in-out infinite' }} />
        </div>
        <div className="px-4 py-4 space-y-3">
          <div className="h-3 w-64 rounded" style={{ background: '#E5E7EB', animation: 'pulse 1.5s ease-in-out infinite' }} />
          <div className="h-5 w-40 rounded" style={{ background: '#E5E7EB', animation: 'pulse 1.5s ease-in-out infinite' }} />
          <div className="flex gap-2">
            {[1,2,3,4].map(i => <div key={i} className="h-6 w-16 rounded" style={{ background: '#E5E7EB', animation: 'pulse 1.5s ease-in-out infinite' }} />)}
          </div>
        </div>
      </div>
    );
  }

  // Empty state — no predictions yet
  if (predictions.length === 0) {
    return (
      <div className="bg-white rounded-xl overflow-hidden" style={{ border: '1px solid #e5e7eb' }}>
        <div className="px-4 py-3 flex items-center justify-between" style={{ borderBottom: '1px solid #f3f4f6' }}>
          <div className="flex items-center gap-2">
            <span className="text-sm font-semibold" style={{ color: NAVY }}>{'\u26A1'} Portfolio Risk Forecast</span>
          </div>
          <span className="text-[10px] font-semibold px-2 py-0.5 rounded" style={{ background: '#F3F4F6', color: '#6B7280' }}>
            rules-v1
          </span>
        </div>
        <div className="px-4 py-5 text-center">
          <p className="text-xs" style={{ color: '#6B7F96', lineHeight: 1.6 }}>
            Risk forecasts generate automatically. Check back after your first compliance logs.
          </p>
        </div>
      </div>
    );
  }

  const hr = highestRisk!;
  const hrColors = RISK_COLORS[hr.risk_level] || RISK_COLORS.unknown;
  const pct = Math.round(hr.failure_probability * 100);

  return (
    <div className="bg-white rounded-xl overflow-hidden" style={{ border: '1px solid #e5e7eb' }}>
      {/* Header */}
      <div className="px-4 py-3 flex items-center justify-between" style={{ borderBottom: '1px solid #f3f4f6' }}>
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold" style={{ color: NAVY }}>{'\u26A1'} Portfolio Risk Forecast</span>
        </div>
        <span
          className="text-[10px] font-semibold px-2 py-0.5 rounded cursor-default"
          style={{ background: '#F3F4F6', color: '#6B7280' }}
          title="Predictions generated by rules engine. ML upgrade ships at 25+ customers."
        >
          rules-v1
        </span>
      </div>

      {/* Body */}
      <div className="px-4 py-3 space-y-3">
        {/* Highest risk location */}
        <div>
          <p className="text-[11px] font-medium" style={{ color: '#6B7F96' }}>Highest risk location:</p>
          <p className="text-sm font-bold mt-0.5" style={{ color: NAVY }}>
            {hr.location_name || 'Unknown Location'} {'\u2014'} {pct}% failure probability
          </p>
          <div className="flex items-center gap-2 mt-1.5">
            <span
              className="text-[11px] font-bold px-2 py-0.5 rounded uppercase"
              style={{ background: hrColors.bg, color: hrColors.text }}
            >
              {hr.risk_level}
            </span>
            <span className="text-[11px] font-semibold" style={{
              color: hr.score_trajectory === 'improving' ? '#16A34A'
                : hr.score_trajectory === 'declining' ? '#DC2626' : '#6B7280',
            }}>
              {hr.score_trajectory === 'improving' ? '\u2191' : hr.score_trajectory === 'declining' ? '\u2193' : '\u2192'}{' '}
              {hr.score_trajectory}
            </span>
          </div>
        </div>

        {/* Risk level distribution */}
        <div className="flex gap-2">
          {([
            { key: 'critical', label: 'critical', count: riskCounts.critical, color: '#DC2626', bg: '#FEF2F2' },
            { key: 'high', label: 'high', count: riskCounts.high, color: '#C2410C', bg: '#FFF7ED' },
            { key: 'moderate', label: 'moderate', count: riskCounts.moderate, color: '#D97706', bg: '#FFFBEB' },
            { key: 'low', label: 'low', count: riskCounts.low, color: '#16A34A', bg: '#F0FDF4' },
          ] as const).map(r => (
            <span
              key={r.key}
              className="text-[10px] font-bold px-2 py-1 rounded"
              style={{ background: r.bg, color: r.color }}
            >
              {r.label}: {r.count}
            </span>
          ))}
        </div>

        {/* Link */}
        <button
          type="button"
          onClick={() => navigate('/intelligence')}
          className="text-xs font-semibold cursor-pointer"
          style={{ color: GOLD, background: 'none', border: 'none', padding: 0 }}
        >
          View Full Forecast {'\u2192'}
        </button>
      </div>
    </div>
  );
}
