-- Migration: add_business_hours_to_locations
-- Status: APPLIED — placeholder file
-- Original timestamp: 20260429000011
--
-- This migration's effects are present in PROD but the original file
-- was removed when 14c-1 marked these versions as already-applied
-- (commit 82b83ff). Each version was marked applied via direct INSERT
-- into supabase_migrations.schema_migrations because the schema
-- changes had been applied to PROD via routes outside the supabase
-- CLI workflow during earlier development cycles.
--
-- This placeholder exists so the supabase CLI does not flag this
-- version as a remote-only orphan during db push. The original DDL
-- is documented below for audit and reference. Do not modify or
-- re-apply this file.
--
-- Tracker entry: supabase_migrations.schema_migrations WHERE version = '20260429000011'.
--
-- ── ORIGINAL DDL (recovered from git history) ────────────────────────────
-- Source: 72c9417 (parent of deletion commit 82b83ff)
--
-- -- Add business hours columns to locations.
-- -- Four new columns define each location's operating window:
-- --   business_hours_start     — Opening time (default 07:00).
-- --   business_hours_end       — Closing time (default 22:00).
-- --   business_hours_days      — Day pattern using MTWRFSU (default all days).
-- --   business_hours_timezone  — IANA timezone (NO default).
-- --
-- -- business_hours_timezone has no default — application must set it
-- -- explicitly on every location insert (typically derived from the
-- -- location's address). A wrong timezone silently breaks auto-dispatch
-- -- logic and weekly report scheduling. Operating hours and days have
-- -- safe defaults that can be overridden in the location settings UI.
-- --
-- -- Used by:
-- --   1. Auto-dispatch logic for sensor support tickets — outside business
-- --      hours = auto-dispatch on CRITICAL severity (locked decision).
-- --   2. Day filtering for weekly_report_recipients setup — send_day
-- --      options are filtered to days the location is open.
-- 
-- ALTER TABLE locations
--   ADD COLUMN IF NOT EXISTS business_hours_start time NOT NULL DEFAULT '07:00',
--   ADD COLUMN IF NOT EXISTS business_hours_end time NOT NULL DEFAULT '22:00',
--   ADD COLUMN IF NOT EXISTS business_hours_days text NOT NULL DEFAULT 'MTWRFSU',
--   ADD COLUMN IF NOT EXISTS business_hours_timezone text;
-- 
-- UPDATE locations SET business_hours_timezone = 'America/Los_Angeles' WHERE business_hours_timezone IS NULL;
-- 
-- ALTER TABLE locations ALTER COLUMN business_hours_timezone SET NOT NULL;
--
-- ── END ORIGINAL DDL ─────────────────────────────────────────────────────

-- Intentional no-op so accidental execution does nothing:
SELECT 1 WHERE FALSE;

