-- Seed outreach step 2: client invite email.
-- buildClientInviteEmail() produces the subject and body; this row
-- only exists so the schedule + sign-off panel can manage it.

INSERT INTO public.outreach_steps (
  step_number,
  label,
  email_kind,
  delay_days,
  trigger_type,
  variant_scope,
  subject_template,
  body_template,
  is_active
)
SELECT
  2,
  'Client invite',
  'invite',
  0,
  'manual',
  'warm',
  '',
  'Body generated by buildClientInviteEmail() — branded invite with compliance rings.',
  true
WHERE NOT EXISTS (
  SELECT 1 FROM public.outreach_steps WHERE step_number = 2
);
