-- Migration: add_menu_items_and_menu_item_id_fk
-- Status: APPLIED — placeholder file
-- Original timestamp: 20260429000025
--
-- This migration's effects are present in PROD but the original file
-- was removed when 14c-1 marked these versions as already-applied
-- (commit 82b83ff). Each version was marked applied via direct INSERT
-- into supabase_migrations.schema_migrations because the schema
-- changes had been applied to PROD via routes outside the supabase
-- CLI workflow during earlier development cycles.
--
-- This placeholder exists so the supabase CLI does not flag this
-- version as a remote-only orphan during db push. The original DDL
-- is documented below for audit and reference. Do not modify or
-- re-apply this file.
--
-- Tracker entry: supabase_migrations.schema_migrations WHERE version = '20260429000025'.
--
-- ── ORIGINAL DDL (recovered from git history) ────────────────────────────
-- Source: 72c9417 (parent of deletion commit 82b83ff)
--
-- -- Migration: Add menu_items table + menu_item_id FK on reading tables
-- -- Why: Phase 1 Item Picker shows BOTH universal HACCP categories AND the
-- --      customer's actual menu items (locked decision 1c). This commit lands
-- --      the menu side: menu_items table holding "Beef Stew", "Mac & Cheese",
-- --      etc., plus a nullable menu_item_id FK on three reading tables that
-- --      capture food-related temperatures.
-- -- Design notes:
-- --   - menu_items is location-scoped via user_location_access RLS pattern
-- --   - default_cook_target_f optional, used by AI suggestions ("poultry 165°F")
-- --   - is_active soft delete preserves audit history
-- --   - unique active name per location prevents duplicates without blocking
-- --     legitimate renames of deactivated items
-- -- Cross-references:
-- --   - Phase 1 Schema Sprint commit 6 (item_category enum + CHECK constraint
-- --     enforcing "exactly one of menu_item_id or item_category" populated)
-- --   - cooldown_temp_checks intentionally NOT touched — inherits food identity
-- --     from parent cooldown_logs.food_batch_id
-- 
-- -- ── menu_items table ─────────────────────────────────────────────────
-- 
-- CREATE TABLE menu_items (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
--   location_id UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
--   name TEXT NOT NULL,
--   description TEXT NULL,
--   category TEXT NULL,
--   default_cook_target_f NUMERIC NULL,
--   is_active BOOLEAN NOT NULL DEFAULT true,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--   updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--   created_by UUID NULL REFERENCES user_profiles(id) ON DELETE SET NULL
-- );
-- 
-- CREATE INDEX idx_menu_items_location_id
--   ON menu_items(location_id);
-- 
-- CREATE INDEX idx_menu_items_organization_id
--   ON menu_items(organization_id);
-- 
-- CREATE INDEX idx_menu_items_active
--   ON menu_items(location_id, is_active);
-- 
-- CREATE UNIQUE INDEX menu_items_active_name_per_location_uq
--   ON menu_items(location_id, name)
--   WHERE is_active = true;
-- 
-- ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
-- 
-- CREATE POLICY menu_items_select ON menu_items
--   FOR SELECT
--   USING (
--     location_id IN (
--       SELECT location_id FROM user_location_access
--       WHERE user_id = auth.uid()
--     )
--   );
-- 
-- CREATE POLICY menu_items_insert ON menu_items
--   FOR INSERT
--   WITH CHECK (
--     location_id IN (
--       SELECT location_id FROM user_location_access
--       WHERE user_id = auth.uid()
--     )
--   );
-- 
-- CREATE POLICY menu_items_update ON menu_items
--   FOR UPDATE
--   USING (
--     location_id IN (
--       SELECT location_id FROM user_location_access
--       WHERE user_id = auth.uid()
--     )
--   )
--   WITH CHECK (
--     location_id IN (
--       SELECT location_id FROM user_location_access
--       WHERE user_id = auth.uid()
--     )
--   );
-- 
-- CREATE POLICY menu_items_delete ON menu_items
--   FOR DELETE
--   USING (
--     location_id IN (
--       SELECT location_id FROM user_location_access
--       WHERE user_id = auth.uid()
--     )
--   );
-- 
-- -- ── menu_item_id FK on three reading tables ──────────────────────────
-- 
-- ALTER TABLE temperature_logs
--   ADD COLUMN menu_item_id UUID NULL;
-- 
-- ALTER TABLE temperature_logs
--   ADD CONSTRAINT temperature_logs_menu_item_id_fkey
--     FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE SET NULL;
-- 
-- CREATE INDEX idx_temperature_logs_menu_item_id
--   ON temperature_logs(menu_item_id)
--   WHERE menu_item_id IS NOT NULL;
-- 
-- ALTER TABLE receiving_temp_logs
--   ADD COLUMN menu_item_id UUID NULL;
-- 
-- ALTER TABLE receiving_temp_logs
--   ADD CONSTRAINT receiving_temp_logs_menu_item_id_fkey
--     FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE SET NULL;
-- 
-- CREATE INDEX idx_receiving_temp_logs_menu_item_id
--   ON receiving_temp_logs(menu_item_id)
--   WHERE menu_item_id IS NOT NULL;
-- 
-- ALTER TABLE cooldown_logs
--   ADD COLUMN menu_item_id UUID NULL;
-- 
-- ALTER TABLE cooldown_logs
--   ADD CONSTRAINT cooldown_logs_menu_item_id_fkey
--     FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE SET NULL;
-- 
-- CREATE INDEX idx_cooldown_logs_menu_item_id
--   ON cooldown_logs(menu_item_id)
--   WHERE menu_item_id IS NOT NULL;
--
-- ── END ORIGINAL DDL ─────────────────────────────────────────────────────

-- Intentional no-op so accidental execution does nothing:
SELECT 1 WHERE FALSE;

