-- Migration: add_step_and_ccp_to_cooldown_logs
-- Status: APPLIED — placeholder file
-- Original timestamp: 20260429000022
--
-- This migration's effects are present in PROD but the original file
-- was removed when 14c-1 marked these versions as already-applied
-- (commit 82b83ff). Each version was marked applied via direct INSERT
-- into supabase_migrations.schema_migrations because the schema
-- changes had been applied to PROD via routes outside the supabase
-- CLI workflow during earlier development cycles.
--
-- This placeholder exists so the supabase CLI does not flag this
-- version as a remote-only orphan during db push. The original DDL
-- is documented below for audit and reference. Do not modify or
-- re-apply this file.
--
-- Tracker entry: supabase_migrations.schema_migrations WHERE version = '20260429000022'.
--
-- ── ORIGINAL DDL (recovered from git history) ────────────────────────────
-- Source: 72c9417 (parent of deletion commit 82b83ff)
--
-- -- Migration: Add step + derived ccp_number on cooldown_logs
-- -- Why: Closes structural gap surfaced during commit 4 inspection.
-- --      cooldown_logs is purpose-built for the Cooldown Step, so step defaults
-- --      to 'cooldown' and ccp_number is constant 4 (every row in this table
-- --      is CCP 4). Honors "capture once, surface everywhere" — CCP 4 reports
-- --      query this table directly via the parent row, with checkpoint reads
-- --      joined from cooldown_temp_checks.
-- -- CCP mapping (locked from dev/test transfer doc):
-- --   cooldown = CCP 4 (this table, every row)
-- -- Cross-references:
-- --   - Phase 1 Schema Sprint commit 1 (haccp_step enum)
-- --   - Phase 1 Schema Sprint commit 2 (same shape on temperature_logs)
-- --   - Phase 1 Schema Sprint commit 3 (same shape on receiving_temp_logs)
-- --   - Phase 1 Schema Sprint commit 4 (override columns + dedupe indexes,
-- --     covers cooldown_logs AND cooldown_temp_checks)
-- -- Pre-launch context: cooldown_logs has 0 rows, NOT NULL DEFAULT is safe.
-- 
-- ALTER TABLE cooldown_logs
--   ADD COLUMN step haccp_step NOT NULL DEFAULT 'cooldown';
-- 
-- ALTER TABLE cooldown_logs
--   ADD COLUMN ccp_number SMALLINT
--   GENERATED ALWAYS AS (4) STORED;
-- 
-- CREATE INDEX idx_cooldown_logs_step
--   ON cooldown_logs(step);
--
-- ── END ORIGINAL DDL ─────────────────────────────────────────────────────

-- Intentional no-op so accidental execution does nothing:
SELECT 1 WHERE FALSE;

