-- Predictive Alerts Table
-- Stores alerts generated by the generate-alerts edge function.
-- Triggered daily by pg_cron, checks documents, vendor services,
-- temp logs, checklists, certifications, and inspections.

CREATE TABLE IF NOT EXISTS predictive_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  location_id text NOT NULL,
  alert_type text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('high', 'medium', 'low')),
  title text NOT NULL,
  description text NOT NULL,
  recommended_action text NOT NULL,
  related_id text,
  related_type text,
  data_points jsonb NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'snoozed', 'dismissed', 'resolved')),
  snoozed_until timestamptz,
  resolved_at timestamptz,
  resolved_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_org_id ON predictive_alerts(organization_id);
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_org_status ON predictive_alerts(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_type_related ON predictive_alerts(alert_type, related_id);
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_severity ON predictive_alerts(organization_id, severity) WHERE status = 'active';

-- Row Level Security
ALTER TABLE predictive_alerts ENABLE ROW LEVEL SECURITY;

-- Users can view alerts for their own organization
DO $$ BEGIN
  DROP POLICY IF EXISTS "Users can view own org alerts" ON predictive_alerts;
  CREATE POLICY "Users can view own org alerts"
    ON predictive_alerts FOR SELECT
    USING (
      organization_id IN (
        SELECT organization_id FROM user_profiles WHERE id = auth.uid()
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can update (dismiss/snooze/resolve) alerts for their own organization
DO $$ BEGIN
  DROP POLICY IF EXISTS "Users can update own org alerts" ON predictive_alerts;
  CREATE POLICY "Users can update own org alerts"
    ON predictive_alerts FOR UPDATE
    USING (
      organization_id IN (
        SELECT organization_id FROM user_profiles WHERE id = auth.uid()
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Service role (edge functions) can insert for any organization
-- Handled automatically by the service_role key used in edge functions

-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION update_predictive_alerts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_predictive_alerts_updated_at ON predictive_alerts;
CREATE TRIGGER trg_predictive_alerts_updated_at
  BEFORE UPDATE ON predictive_alerts
  FOR EACH ROW EXECUTE FUNCTION update_predictive_alerts_updated_at();

-- pg_cron schedule (run manually on first deploy):
-- SELECT cron.schedule(
--   'generate-predictive-alerts',
--   '0 6 * * *',
--   $$
--     SELECT net.http_post(
--       url := 'https://<project-ref>.supabase.co/functions/v1/generate-alerts',
--       headers := jsonb_build_object(
--         'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key'),
--         'Content-Type', 'application/json'
--       ),
--       body := jsonb_build_object('organization_id', org.id)
--     )
--     FROM organizations org
--     WHERE org.status = 'active';
--   $$
-- );
