-- ═══════════════════════════════════════════════════════════════════════
-- SEED — outreach_steps step 1: County briefing (email #1 for all)
--
-- trigger_type = 'manual': first real send goes to ~70 CPP clients.
-- Manual keeps a deliberate send gate so cron cannot fire unattended.
-- Flip to 'auto' after a batch has been watched land cleanly.
--
-- variant_scope = 'both': the county briefing is email #1 for warm AND
-- cold recipients. Cold recipients are still skipped at send time by
-- the existing cron guard (variant='cold' → held) and exported to
-- HubSpot via the cold-handoff panel.
--
-- body_template is a marker string — buildBriefingEmail() is hardwired
-- as the only body source. The template field cannot hold the body
-- because it is code-generated from live jurisdiction data.
--
-- Guard: skip if step_number 1 already exists (idempotent).
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO outreach_steps (
  step_number,
  label,
  delay_days,
  trigger_type,
  variant_scope,
  subject_template,
  body_template,
  is_active
)
SELECT
  1,
  'County briefing',
  0,
  'manual',
  'both',
  '{{COUNTY}} County Briefing — How {{COUNTY}} County Evaluates Commercial Kitchens',
  'Body generated by buildBriefingEmail() — per-county evaluation block cannot be a static template.',
  true
WHERE NOT EXISTS (
  SELECT 1 FROM outreach_steps WHERE step_number = 1
);
