-- ============================================================
-- deficiency_resolution_plans — AI-drafted resolution plans
-- Stores step-by-step correction plans generated by Claude,
-- linked 1:1 to a deficiency. Org isolation via deficiency FK.
-- ============================================================

CREATE TABLE IF NOT EXISTS deficiency_resolution_plans (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deficiency_id               UUID NOT NULL UNIQUE
                                REFERENCES deficiencies(id) ON DELETE CASCADE,

  -- Drafted corrective action fields (pre-acceptance preview)
  drafted_ca_title            TEXT NOT NULL,
  drafted_ca_severity         TEXT NOT NULL CHECK (drafted_ca_severity IN ('critical','major','minor','advisory')),
  drafted_ca_category         TEXT NOT NULL,
  drafted_ca_assignee_id      UUID,
  drafted_ca_due_date         DATE,

  -- Step-by-step plan (array of step objects)
  steps                       JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- AI metadata
  ai_model                    TEXT NOT NULL,
  ai_prompt_version           TEXT NOT NULL,

  -- Acceptance lifecycle
  accepted_at                 TIMESTAMPTZ,
  accepted_by                 UUID,
  created_corrective_action_id UUID,

  -- Timestamps
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for deficiency lookups
CREATE INDEX IF NOT EXISTS idx_def_res_plans_deficiency
  ON deficiency_resolution_plans (deficiency_id);

-- RLS: org isolation via deficiency → organization_id
ALTER TABLE deficiency_resolution_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view their deficiency plans"
  ON deficiency_resolution_plans FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM deficiencies d
      WHERE d.id = deficiency_resolution_plans.deficiency_id
        AND d.organization_id = (
          SELECT organization_id FROM user_profiles
          WHERE id = auth.uid()
        )
    )
  );

CREATE POLICY "Org members can insert deficiency plans"
  ON deficiency_resolution_plans FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM deficiencies d
      WHERE d.id = deficiency_resolution_plans.deficiency_id
        AND d.organization_id = (
          SELECT organization_id FROM user_profiles
          WHERE id = auth.uid()
        )
    )
  );

CREATE POLICY "Org members can update their deficiency plans"
  ON deficiency_resolution_plans FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM deficiencies d
      WHERE d.id = deficiency_resolution_plans.deficiency_id
        AND d.organization_id = (
          SELECT organization_id FROM user_profiles
          WHERE id = auth.uid()
        )
    )
  );

-- Service role bypass for edge functions
CREATE POLICY "Service role full access to deficiency plans"
  ON deficiency_resolution_plans FOR ALL
  USING (auth.role() = 'service_role');

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_def_res_plan_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_def_res_plan_updated_at
  BEFORE UPDATE ON deficiency_resolution_plans
  FOR EACH ROW EXECUTE FUNCTION update_def_res_plan_updated_at();
